version: "2"
volumes:
  vendor_dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/eldad/go/src/github.com/eldad87/go-boilerplate/vendor"
services:
  app:
    environment:
      - APP_NAME=boilerplate
      - BUILD_ENV=development
      - LOG_LEVEL=debug
      - DATABASE_DRIVER=mysql
      - DATABASE_DSN=root:password@tcp(127.0.0.1:3306)/boilerplate
      # Producer & Consumer
      - MACHINERY_BROKER__DSN=amqp://rabbitmq:rabbitmq@rabbit:5672
      - MACHINERY_DEFAULT__QUEUE=boilerplate
      - MACHINERY_RESULT__BACKEND__DSN=redis://redis:6379
      - MACHINERY_EXCHANGE=boilerplate
      - MACHINERY_EXCHANGE__TYPE=direct
      # Producer
      - MACHINERY_BINDING__KEY=boilerplate
      # Consumer
      - MACHINERY_CONSUMER_ENABLE=1
      - MACHINERY_CONSUMER_TAG=default-01
      - MACHINERY_CONSUMER_CONCURRENT__TASKS=10
      - MACHINERY_CONSUMER_PREFETCH__COUNT=1
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        build_env: 'development'
        app_port: 8080
    security_opt:
      - seccomp:unconfined
    volumes:
      - vendor_dir:/go/src/github.com/eldad87/go-boilerplate/vendor
      - ./src:/go/src/github.com/eldad87/go-boilerplate/src
      - ./Gopkg.lock:/go/src/github.com/eldad87/go-boilerplate/Gopkg.lock
      - ./Gopkg.toml:/go/src/github.com/eldad87/go-boilerplate/Gopkg.toml
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - rabbit
      - db
  redis:
    image: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
    - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5578"
      - "16686:16686"
      - "14268:14268"
  db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: boilerplate
      MYSQL_DATABASE: boilerplate
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    tty: true
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
