version: "2"
services:
  app:
    environment:
      app_name: 'boilerplate'
      build_env: 'development'
      log_level: 'debug'
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        build_env: 'development'
        app_port: 8080
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./src:/go/src/github.com/eldad87/go-boilerplate/src
      - ./Gopkg.lock:/go/src/github.com/eldad87/go-boilerplate/Gopkg.lock
      - ./Gopkg.toml:/go/src/github.com/eldad87/go-boilerplate/Gopkg.toml
    ports:
      - "8080:8080"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5578"
      - "16686:16686"
      - "14268:14268"