FROM golang:1.14.2 as builder

# Arguments to Env variables
ARG build_env
ARG app_port
ARG app_grpc_port
ARG protobuf_release_tag
ARG app_cmd

ENV BUILD_ENV $build_env
ENV APP_PORT $app_port
ENV APP_GRPC_PORT $app_grpc_port
ENV PROTOBUF_RELEASE_TAG $protobuf_release_tag
ENV APP_CMD $app_cmd

# Path
ENV GOBIN=$GOPATH/bin
ENV PATH=$PATH:$GOBIN
WORKDIR $GOPATH/src/github.com/eldad87/go-boilerplate

# Protobuf
RUN apt-get update && \
    apt-get -y install unzip
RUN curl -OL "https://github.com/google/protobuf/releases/download/v${PROTOBUF_RELEASE_TAG}/protoc-${PROTOBUF_RELEASE_TAG}-linux-x86_64.zip" && \
    unzip "protoc-${PROTOBUF_RELEASE_TAG}-linux-x86_64.zip" -d protoc3 && \
    mv protoc3/bin/* /usr/local/bin/ && \
    mv protoc3/include/* /usr/local/include/ && \
    rm -rf protoc3 && \
    rm protoc-${PROTOBUF_RELEASE_TAG}-linux-x86_64.zip

# RUN go mod init
RUN go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
RUN go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
RUN go get -u github.com/srikrsna/protoc-gen-gotag
RUN go get -d github.com/envoyproxy/protoc-gen-validate && make build -C /go/src/github.com/envoyproxy/protoc-gen-validate/
RUN go get -u github.com/golang/protobuf/protoc-gen-go

# SQLBoiler
RUN GO111MODULE=off go get -u -t github.com/volatiletech/sqlboiler
# Also install the driver of your choice, there exists pqsl, mysql, mssql
RUN GO111MODULE=off go get github.com/volatiletech/sqlboiler/drivers/sqlboiler-mysql

# Go based task runner
RUN git clone https://github.com/magefile/mage
RUN cd mage && go run bootstrap.go
RUN cd $GOPATH/src/github.com/eldad87/go-boilerplate && rm -rf mage

# Dep
ADD go.mod go.mod
ADD go.sum go.sum
Run go mod download

# Install the correct protoc-gen-go in the correct version
# RUN go install ./vendor/github.com/golang/protobuf/protoc-gen-go/

# Copy our code
Add src/ src/

# Build or install hot-reload
RUN go get -u github.com/VojtechVitek/rerun/cmd/rerun

# Run download deps, sync vendor folder to host and binary hot-reload
CMD go mod download && rerun -watch ./ -ignore vendor vendor_host bin migration -run go run ./src/cmd/${APP_CMD}/app.go

EXPOSE ${APP_GRPC_PORT} ${APP_PORT}