version: "2"
volumes:
  vendor_dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/eldad/go/src/github.com/eldad87/go-boilerplate/vendor"
services:
  app:
    environment:
      - APP_NAME=boilerplate
      - APP_PORT=8080
      - APP_GRPC_PORT=8082
      - APP_GRPC_HTTP__ROUTE__PREFIX=/v1
      - APP_REQUEST_TIMEOUT=500
      - APP_REQUEST_MAX__CONN=30
      - APP_REQUEST_MAX__VOL_THRESHOLD=20
      - APP_REQUEST_MAX__SLEEP__WINDOW=5000
      - APP_REQUEST_MAX__ERR_PER_THRESHOLD=50
      - BUILD_ENV=development
      - LOG_LEVEL=debug
      - SENTRY_DSN=https://67c018312d4d47978d223e80f4c2e896@sentry.io/1305039
      - SENTRY_LOG__LEVEL=error
      - DATABASE_DRIVER=mysql
      - DATABASE_DSN=root:root@tcp(db:3306)/boilerplate?charset=utf8&parseTime=True&loc=UTC&multiStatements=true
      # OpenTracing
      - OPENTRACING_JAEGER_HOST=jaeger
      - OPENTRACING_JAEGER_PORT=6831
      # Health Check
      - HEALTH__CHECK_GOROUTINE__THRESHOLD=100
      # Producer & Consumer
      ## Broker Producer limitation
      - MACHINERY_BROKER_RETRIES=2
      - MACHINERY_BROKER_RETRY__DELAY=50
      - MACHINERY_BROKER_TIMEOUT=100
      - MACHINERY_BROKER_MAX_CONN=100
      - MACHINERY_BROKER_VOL_THRESHOLD=20
      - MACHINERY_BROKER_SLEEP__WINDOW=5000
      - MACHINERY_BROKER_ERR_PER_THRESHOLD=50
      ## Other
      - MACHINERY_BROKER__DSN=amqp://rabbitmq:rabbitmq@rabbit:5672
      - MACHINERY_DEFAULT__QUEUE=boilerplate
      - MACHINERY_RESULT__BACKEND__DSN=redis://redis:6379
      - MACHINERY_EXCHANGE=boilerplate
      - MACHINERY_EXCHANGE__TYPE=direct
      # Producer
      - MACHINERY_BINDING__KEY=boilerplate
      # Consumer
      - MACHINERY_CONSUMER_ENABLE=1
      - MACHINERY_CONSUMER_TAG=default-01
      - MACHINERY_CONSUMER_CONCURRENT__TASKS=10
      - MACHINERY_CONSUMER_PREFETCH__COUNT=1
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        build_env: 'development'
        app_port: 8080
        app_grpc_port: 8082
        protobuf_release_tag: '3.6.1'
        proto_gen_release_tag: '1.2.0'
    security_opt:
      - seccomp:unconfined
    volumes:
      - vendor_dir:/go/src/github.com/eldad87/go-boilerplate/vendor
      - ./src:/go/src/github.com/eldad87/go-boilerplate/src
      - ./Gopkg.lock:/go/src/github.com/eldad87/go-boilerplate/Gopkg.lock
      - ./Gopkg.toml:/go/src/github.com/eldad87/go-boilerplate/Gopkg.toml
      - ./src/config/development/sqlboiler.yaml:/go/src/github.com/eldad87/go-boilerplate/sqlboiler.yaml
    ports:
      - "8080:8080"
      - "8082:8082"
    depends_on:
      - redis
      - rabbit
      - db
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - API_URL=http://localhost:8080/swaggerui/swagger.json
    expose:
      - 8080
    depends_on:
      - app
  redis:
    image: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
    - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8083:8081"
    links:
      - redis
    depends_on:
      - redis
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5578"
      - "16686:16686"
      - "14268:14268"
  db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boilerplate
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    tty: true
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
