// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/transport/grpc/proto/visit_transport.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ID struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_468c54e0734da02a, []int{0}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type VisitRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitRequest) Reset()         { *m = VisitRequest{} }
func (m *VisitRequest) String() string { return proto.CompactTextString(m) }
func (*VisitRequest) ProtoMessage()    {}
func (*VisitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_468c54e0734da02a, []int{1}
}

func (m *VisitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitRequest.Unmarshal(m, b)
}
func (m *VisitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitRequest.Marshal(b, m, deterministic)
}
func (m *VisitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitRequest.Merge(m, src)
}
func (m *VisitRequest) XXX_Size() int {
	return xxx_messageInfo_VisitRequest.Size(m)
}
func (m *VisitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VisitRequest proto.InternalMessageInfo

func (m *VisitRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VisitRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *VisitRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type VisitResponse struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VisitResponse) Reset()         { *m = VisitResponse{} }
func (m *VisitResponse) String() string { return proto.CompactTextString(m) }
func (*VisitResponse) ProtoMessage()    {}
func (*VisitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_468c54e0734da02a, []int{2}
}

func (m *VisitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitResponse.Unmarshal(m, b)
}
func (m *VisitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitResponse.Marshal(b, m, deterministic)
}
func (m *VisitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitResponse.Merge(m, src)
}
func (m *VisitResponse) XXX_Size() int {
	return xxx_messageInfo_VisitResponse.Size(m)
}
func (m *VisitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VisitResponse proto.InternalMessageInfo

func (m *VisitResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VisitResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *VisitResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *VisitResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *VisitResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*ID)(nil), "pb.ID")
	proto.RegisterType((*VisitRequest)(nil), "pb.VisitRequest")
	proto.RegisterType((*VisitResponse)(nil), "pb.VisitResponse")
}

func init() {
	proto.RegisterFile("src/transport/grpc/proto/visit_transport.proto", fileDescriptor_468c54e0734da02a)
}

var fileDescriptor_468c54e0734da02a = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x6e, 0xd4, 0x30,
	0x18, 0xc5, 0x89, 0xa7, 0x14, 0x62, 0x68, 0x34, 0x78, 0x01, 0xa3, 0x40, 0x61, 0x14, 0x55, 0x28,
	0xaa, 0x54, 0x5b, 0x94, 0x0d, 0xb0, 0x9b, 0xaa, 0x12, 0xea, 0x06, 0xa1, 0x50, 0xb1, 0x60, 0x33,
	0x72, 0x12, 0x37, 0x58, 0x9a, 0xd8, 0xc6, 0xfe, 0x12, 0x51, 0x21, 0x36, 0x5c, 0x81, 0x2d, 0x97,
	0x42, 0x5c, 0x81, 0x53, 0xb0, 0x42, 0x71, 0x92, 0xb6, 0xa3, 0x01, 0x75, 0x95, 0x3f, 0xef, 0xf7,
	0xde, 0xb3, 0xfd, 0x19, 0x53, 0x67, 0x0b, 0x06, 0x96, 0x2b, 0x67, 0xb4, 0x05, 0x56, 0x59, 0x53,
	0x30, 0x63, 0x35, 0x68, 0xd6, 0x4a, 0x27, 0x61, 0x79, 0x21, 0x51, 0xff, 0x97, 0x20, 0x93, 0xc7,
	0x4f, 0x2a, 0xad, 0xab, 0x95, 0xe8, 0xb9, 0xbc, 0x39, 0x63, 0x20, 0x6b, 0xe1, 0x80, 0xd7, 0xa6,
	0x87, 0xe2, 0x47, 0x03, 0xc0, 0x8d, 0x64, 0x5c, 0x29, 0x0d, 0x1c, 0xa4, 0x56, 0x6e, 0x50, 0x17,
	0x95, 0x84, 0x8f, 0x4d, 0x4e, 0x0b, 0x5d, 0x33, 0xa1, 0x5a, 0x7d, 0x6e, 0xac, 0xfe, 0x7c, 0xde,
	0xa7, 0x15, 0x07, 0x95, 0x50, 0x07, 0x2d, 0x5f, 0xc9, 0x92, 0x83, 0x60, 0x1b, 0x2f, 0x7d, 0x44,
	0xb2, 0x8b, 0xd1, 0xc9, 0x31, 0x79, 0x80, 0x91, 0x2c, 0x67, 0xc1, 0x3c, 0x48, 0x77, 0x8e, 0x6e,
	0xfd, 0x39, 0xda, 0xda, 0x47, 0xe9, 0x8d, 0x0c, 0xc9, 0x32, 0x69, 0xf0, 0xdd, 0xf7, 0xdd, 0xea,
	0x33, 0xf1, 0xa9, 0x11, 0x0e, 0xfe, 0x0b, 0x92, 0xa7, 0x18, 0x9f, 0x49, 0xeb, 0x60, 0xa9, 0x78,
	0x2d, 0x66, 0x68, 0x1e, 0xa4, 0xa1, 0x07, 0x2c, 0x9a, 0xa2, 0x2c, 0xf4, 0xd2, 0x1b, 0x5e, 0x0b,
	0xb2, 0x87, 0xc3, 0x15, 0x1f, 0xb1, 0xc9, 0x3a, 0x76, 0xbb, 0x53, 0x3a, 0x2a, 0xf9, 0x19, 0xe0,
	0x9d, 0xa1, 0xd7, 0x19, 0xad, 0x9c, 0x20, 0xd1, 0x65, 0xb1, 0xef, 0xdb, 0xdd, 0xec, 0xbb, 0x5a,
	0xf3, 0x70, 0xa3, 0xe6, 0x32, 0x9d, 0xbc, 0xc4, 0xb8, 0xb0, 0x82, 0x83, 0x28, 0x97, 0x1c, 0x66,
	0x5b, 0xf3, 0x20, 0xbd, 0x73, 0x18, 0xd3, 0xfe, 0xa4, 0xe9, 0x38, 0x0a, 0x7a, 0x3a, 0x8e, 0x22,
	0x0b, 0x07, 0x7a, 0x01, 0x9d, 0xb5, 0x31, 0xe5, 0x68, 0xbd, 0x79, 0xbd, 0x75, 0xa0, 0x17, 0x70,
	0xf8, 0x23, 0xc0, 0x91, 0xdf, 0xd3, 0xe9, 0x78, 0x11, 0xc8, 0x0b, 0x3c, 0x79, 0x2d, 0x80, 0x6c,
	0x53, 0x93, 0xd3, 0x93, 0xe3, 0xf8, 0x5e, 0xf7, 0x5c, 0xdb, 0x76, 0x72, 0xff, 0xdb, 0xaf, 0xdf,
	0xdf, 0xd1, 0x94, 0x44, 0xac, 0x7d, 0xd6, 0xdf, 0x23, 0xf6, 0x45, 0x96, 0x5f, 0xc9, 0x5b, 0x3c,
	0x79, 0x27, 0x80, 0x4c, 0xaf, 0x38, 0xfc, 0x80, 0xfe, 0x95, 0xb1, 0xe7, 0x33, 0x1e, 0x27, 0xe1,
	0x45, 0xc6, 0xab, 0x60, 0xff, 0x43, 0x14, 0xaf, 0x7d, 0xe7, 0xdb, 0x7e, 0xf5, 0xcf, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x3a, 0x6e, 0xf7, 0xa5, 0xc7, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VisitTransportClient is the client API for VisitTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VisitTransportClient interface {
	// Simple return the visit id
	Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*VisitResponse, error)
	// Update/Create a device
	Set(ctx context.Context, in *VisitRequest, opts ...grpc.CallOption) (*VisitResponse, error)
}

type visitTransportClient struct {
	cc *grpc.ClientConn
}

func NewVisitTransportClient(cc *grpc.ClientConn) VisitTransportClient {
	return &visitTransportClient{cc}
}

func (c *visitTransportClient) Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*VisitResponse, error) {
	out := new(VisitResponse)
	err := c.cc.Invoke(ctx, "/pb.VisitTransport/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visitTransportClient) Set(ctx context.Context, in *VisitRequest, opts ...grpc.CallOption) (*VisitResponse, error) {
	out := new(VisitResponse)
	err := c.cc.Invoke(ctx, "/pb.VisitTransport/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisitTransportServer is the server API for VisitTransport service.
type VisitTransportServer interface {
	// Simple return the visit id
	Get(context.Context, *ID) (*VisitResponse, error)
	// Update/Create a device
	Set(context.Context, *VisitRequest) (*VisitResponse, error)
}

func RegisterVisitTransportServer(s *grpc.Server, srv VisitTransportServer) {
	s.RegisterService(&_VisitTransport_serviceDesc, srv)
}

func _VisitTransport_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisitTransportServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VisitTransport/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisitTransportServer).Get(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisitTransport_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisitTransportServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VisitTransport/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisitTransportServer).Set(ctx, req.(*VisitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VisitTransport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VisitTransport",
	HandlerType: (*VisitTransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _VisitTransport_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _VisitTransport_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/transport/grpc/proto/visit_transport.proto",
}
